---
name: Build
on:
  workflow_call:
    inputs:
      os:
        description: 'The runner os'
        required: true
        type: string
      build_type:
        description: 'The build type. Muste be Debug or Release'
        required: true
        type: string
      arch:
        description: 'The architecture. Must be 386 or amd64'
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ inputs.os }}
    env:
      CMAKE_INSTALL_PREFIX: ${{ github.workspace }}/install
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3.3.0
        with:
          path: UmatiDashboardOpcUaClient
          submodules: recursive
      - name: Build UmatiDashboardOpcUaClient with dependencies
        run: |
          LIBCPP_VERSION="$(dpkg -s libstdc++6 | grep Version | awk '{match($0,"[0-9]+.[0-9].[0-9]",a)}END{print a[0]}')"
          mkdir -p build
          cd build
          cmake ../UmatiDashboardOpcUaClient/.github/ \ 
            -DCMAKE_INSTALL_PREFIX:PATH="${{ env.CMAKE_INSTALL_PREFIX }}" \
            -DCMAKE_BUILD_TYPE="${{inputs.build_type}}" \
            -DPAHO_WITH_SSL=1 \ 
            -DBUILD_DEB_PACKAGE:BOOL=1 \ 
            -DDEB_PACKAGE_LIBCPP_VERSION="$LIBCPP_VERSION"
          cmake --build . -j --config ${{inputs.build_type}}
          make package
        shell: bash  
      - name: Run Tests
        run: |
          cd build/Dashboard-Client-build
          ctest -V -C "${{inputs.build_type}}"